---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fast-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:marcelomanchester/feature-environments-argocd.git
    targetRevision: HEAD
    path: helm/
    helm:
      parameters:
      - name: "image.tag"
        value: "set-pat-token"
      - name: "namespace"
        value: 'fast-api'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fast-api