apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fast-api
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: marcelomanchester
        repo: feature-environments-argocd
        tokenRef:
          secretName: github-token
          key: token
        labels:
        - environment
      requeueAfterSeconds: 15
  template:
    metadata:
      name: 'fast-api-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'git@github.com:marcelomanchester/feature-environments-argocd.git'
        targetRevision: '{{head_sha}}'
        path: helm/
        helm:
          parameters:
          - name: "image.tag"
            value: "{{branch}}"
          - name: "namespace"
            value: 'fast-api-{{branch}}-{{number}}'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
